# Generated by Django 6.0.2 on 2026-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='code_type',
            field=models.CharField(choices=[('barcode', 'Barcode (Code128)'), ('qrcode', 'QR Code')], default='barcode', max_length=10),
        ),
    ]
